on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: display branch name
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v2
      - name: Bump minor version and push tag
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: leonsteinhaeuser/git-tag-bump@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          bump-type: minor
      - name: Bump patch version and push tag
        if: startsWith(github.ref, 'refs/heads/bugfix/')
        uses: leonsteinhaeuser/git-tag-bump@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          bump-type: patch
