# on:
#   pull_request:
#     types: [closed]
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.pull_request.merged == true }}
#     steps:
#       - name: Get source branch
#         run: echo "The source branch is ${{ github.head_ref }}"

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: ${{ github.head_ref }}
    steps:
      - name: display branch name
        run: | 
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump minor version and push tag
        if: startsWith(env.SOURCE_BRANCH, 'feature/')
        uses: leonsteinhaeuser/git-tag-bump@v1.0.0
        with:
          args: "--bump minor"
      - name: Bump patch version and push tag
        if: startsWith(env.SOURCE_BRANCH, 'bugfix/')
        uses: leonsteinhaeuser/git-tag-bump@v1.0.0
        with:
          args: "--bump patch"
