name: Test workflows
# xxx c
on:
  push:
    branches:
      - 'main'
      
jobs:
  check-db-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write a step summary
        run: echo "*My test*" >> $GITHUB_STEP_SUMMARY

  apply-db-migrations:
    runs-on: ubuntu-latest
    environment: production
    needs: check-db-migrations
    steps:
      - uses: actions/checkout@v3
      - name: pretend to do something
        run: echo "I would apply some migration"
